spring.application.name=exemplo2

# URL de conexão do banco de dados
spring.datasource.url=jdbc:h2:mem:bancoteste

# Define o usúario padrão 
spring.datasource.username=sa

# define a senha do usúario padrão (vazia por padrão)
spring.datasource.password=

# Habilita o console do H2 
spring.h2.console.enable=true

# Define a URL do console 
spring.h2.console.path=/h2-console

# Para o H2 funcionar no codespaces 
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework

# Configura o JPA para atualizar a estrutura de banco 
# automaticamente baseado nas class do java 
spring.jpa.hibernate.ddl-auto=update 